### PR TITLE
fixed #61

### LINKED ISSUE #61: game crashes when two robots move to the same space
no exception but 100% cpu load ...

### PR DESCRIPTION
**Pull request by xithan**

### CODE REVIEW

File: both/gamelogic.js [hunk 1]
```diff
@@ -178,6 +178,7 @@ GameLogic = {
           var step = Math.min(cardType.position, 1);
           for (var j = 0; j < Math.abs(cardType.position); j++) {
             var timeout = j+1 < Math.abs(cardType.position) ? 0 : _CARD_PLAY_DELAY; //don't delay if there is another step to execute
+            var players = Players.find({gameId: player.gameId}).fetch();
             executeStep(players, player, step, timeout);
```
Comment (xithan) [inline both/gamelogic.js]: executeStep uses outdated coordinates if players is not updated here
